# defined github action for build and deployment
on:
  push:
    branches:
      - main # main or master according to your github repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send build request
        env:
          BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          read -r -d '' PAYLOAD <<'JSON'
          {
            "repoName": "${REPO}",
            "event": "main_push",
            "commit": "${SHA}",
          }
          JSON

          curl --fail --show-error --silent \
            --max-time 20 --retry 3 --retry-delay 2 \
            -X POST https://build.wpcustompros.com/build \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${BUILD_TOKEN}" \
            -d "${PAYLOAD}"
