name: Build & Deploy (external builder)

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install jq (just in case)
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y jq
          fi

      - name: Send build request
        env:
          BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        shell: bash
        run: |
          set -euo pipefail

          OWNER="${REPO%%/*}"
          NAME="${REPO##*/}"

          PAYLOAD="$(jq -n \
            --arg owner "$OWNER" \
            --arg repoName "$NAME" \
            --arg sha "$SHA" \
            '{owner: $owner, repoName: $repoName, event: "main_push", commit: $sha}')"

          echo "Sending payload: $(jq -c . <<<"$PAYLOAD")"

          curl --fail --show-error --silent \
            --connect-timeout 5 \
            --max-time 20 \
            --retry 3 --retry-delay 2 \
            -X POST https://build.wpcustompros.com/build \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $BUILD_TOKEN" \
            -d "$PAYLOAD"
